# Generated by Django 3.2 on 2021-07-19 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProject', '0016_alter_shippingaddress_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
