# Generated by Django 3.2 on 2021-07-19 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyProject', '0017_alter_shippingaddress_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='phone',
        ),
    ]
